Repository DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo, pull requests merged in 2023-11, with the labels that each got.

#81 feat: [#78] 측정을 시작하기 전에 값들의 기본값"---"을 설정
  SoccerBeat/SoccerBeat Watch App/View/Progress/BPMTextView.swift
  SoccerBeat/SoccerBeat Watch App/View/Progress/GameProgressView.swift
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/WatchWorkoutManager.swift
Labels: enhancement

#97 feat: [#89] MatchTotalView 작업
  SoccerBeat/Share/Fonts/SF-Pro-Text-LightItalic.otf
  SoccerBeat/Share/Utiles/Color+extension.swift
  SoccerBeat/Share/Utiles/Font+extension.swift
  SoccerBeat/SoccerBeat Watch App/View/PhraseView.swift
  SoccerBeat/SoccerBeat-Watch-App-Info.plist
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/Info.plist
  SoccerBeat/SoccerBeat/UI/Screens/MatchRecapView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchTotalView.swift
Labels: enhancement

#98 feat: [#96] Analytics 중간 커밋
  SoccerBeat/SoccerBeat/UI/Screens/AnalyticsView.swift
Labels: enhancement

#122 feat: [#114] 경기 종료시 route 정보 저장
  SoccerBeat/SoccerBeat Watch App/View/PrecountView.swift
  SoccerBeat/SoccerBeat Watch App/View/StartPauseControll/StartView.swift
  SoccerBeat/SoccerBeat Watch App/View/SummaryView.swift
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/WatchWorkoutManager.swift
  SoccerBeat/SoccerBeat-Watch-App-Info.plist
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
Labels: bug, enhancement, help wanted

#141 feat: [#135] Watch 메인 화면 디자인 리뷰 반영
  SoccerBeat/Share/Utiles/Color+extension.swift
  SoccerBeat/Share/Utiles/ElapsedTimeFormatter.swift
  SoccerBeat/Share/Utiles/Font+extension.swift
  SoccerBeat/Share/Utiles/TextBorder+extension.swift
  SoccerBeat/SoccerBeat Watch App/View/Progress/ElapsedTimeView.swift
  SoccerBeat/SoccerBeat Watch App/View/Progress/GameProgressView.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
Labels: enhancement

#162 feat [#136] 4종류의 차트 데이터를 표여주기
  SoccerBeat/Share/Utiles/Color+extension.swift
  SoccerBeat/Share/Utiles/Double+extension.swift
  SoccerBeat/Share/Utiles/FloatingCapsuleModifier.swift
  SoccerBeat/Share/Utiles/Font+extension.swift
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/WatchWorkoutManager.swift
  SoccerBeat/SoccerBeat-Watch-App-Info.plist
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/Info.plist
  SoccerBeat/SoccerBeat/Interactors/HealthInteractor.swift
  SoccerBeat/SoccerBeat/Resources/Data.swift
  SoccerBeat/SoccerBeat/Resources/WorkoutData.swift
  SoccerBeat/SoccerBeat/SoccerBeatApp.swift
  SoccerBeat/SoccerBeat/UI/Charts/Analyzable.swift
  SoccerBeat/SoccerBeat/UI/Charts/BPMChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/DistanceChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/SpeedChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/SprintChart.swift
  SoccerBeat/SoccerBeat/UI/Screens/AnalyticsDetailView.swift
  SoccerBeat/SoccerBeat/UI/Screens/AnalyticsView.swift
  SoccerBeat/SoccerBeat/UI/Screens/BackgroundImageView.swift
  SoccerBeat/SoccerBeat/UI/Screens/BarMinMaxGraphView.swift
  SoccerBeat/SoccerBeat/UI/Screens/ContentView.swift
  SoccerBeat/SoccerBeat/UI/Screens/LineGraphView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchRecapView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchTotalView.swift
Labels: enhancement

#176 fix: [#168] chart overview default UI
  SoccerBeat/SoccerBeat/Resources/WorkoutData.swift
  SoccerBeat/SoccerBeat/UI/Charts/BPMChartOverview.swift
  SoccerBeat/SoccerBeat/UI/Charts/SprintChartOverview.swift
  SoccerBeat/SoccerBeat/UI/LightRectangleView.swift
  SoccerBeat/SoccerBeat/UI/Screens/AnalyticsView.swift
Labels: enhancement

#182 feat: [#172] highlighter
  SoccerBeat/Share/Model/ActivityEnum.swift
  SoccerBeat/Share/Utiles/HighlightModifier.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/UI/Screens/AnalyticsView.swift
Labels: enhancement

#198 feat: [#191] 트로피 컬렉션 뷰 작업
  SoccerBeat/Share/Model/BadgeImageDictionary.swift
  SoccerBeat/Share/Utiles/HighlightModifier.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/Interactors/HealthInteractor.swift
  SoccerBeat/SoccerBeat/UI/Screens/NilDataView.swift
  SoccerBeat/SoccerBeat/UI/Screens/ProfileView.swift
  SoccerBeat/SoccerBeat/UI/Trophy/TrophyCollectionView.swift
  SoccerBeat/SoccerBeat/UI/Trophy/TrophyView.swift
Labels: enhancement

#204 feat: [#200] 트로피 정보 알림 추가
  SoccerBeat/Share/Model/BadgeImageDictionary.swift
  SoccerBeat/Share/Utiles/Color+extension.swift
  SoccerBeat/Share/Utiles/Font+extension.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/UI/Trophy/TooltipView.swift
  SoccerBeat/SoccerBeat/UI/Trophy/TrophyView.swift
Labels: enhancement

#220 fix: [#219] highlighter adapt
  SoccerBeat/SoccerBeat/UI/Screens/ShareView.swift
Labels: enhancement

#227 fix: [#221] 위치, 건강 권한 요청 로직 수정
  SoccerBeat/SoccerBeat Watch App/View/StartPauseControll/StartView.swift
  SoccerBeat/SoccerBeat Watch App/View/Summary/SummaryView.swift
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/WatchWorkoutManager.swift
  SoccerBeat/SoccerBeat/UI/Screens/NilDataView.swift
Labels: bug, enhancement

#232 fix: [#231] modify general UI
  SoccerBeat/Share/Utiles/Color+extension.swift
  SoccerBeat/SoccerBeat Watch App/View/Progress/ElapsedTimeView.swift
  SoccerBeat/SoccerBeat Watch App/View/Summary/SummaryView.swift
  SoccerBeat/SoccerBeat/UI/Analytics/AnalyticsView.swift
  SoccerBeat/SoccerBeat/UI/Charts/BPMChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/DistanceChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/SpeedChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/SprintChart.swift
  SoccerBeat/SoccerBeat/UI/InfomationButton.swift
  SoccerBeat/SoccerBeat/UI/Screens/MainView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchDetailView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchRecapView.swift
  SoccerBeat/SoccerBeat/UI/Screens/NilDataView.swift
  SoccerBeat/SoccerBeat/UI/Screens/ProfileView.swift
  SoccerBeat/SoccerBeat/UI/Screens/ShareView.swift
  SoccerBeat/SoccerBeat/UI/Trophy/TrophyCollectionView.swift
Labels: bug, enhancement
