Repository DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo, pull requests merged in 2024-03, with the labels that each got.

#267 setting: [#214] 프로비저닝 프로파일 추가
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
Labels: enhancement

#269 refactor: [#265] WorkoutManager를 쪼개기
  SoccerBeat/SoccerBeat Watch App/SoccerBeatApp.swift
  SoccerBeat/SoccerBeat Watch App/View/Progress/GameProgressView.swift
  SoccerBeat/SoccerBeat Watch App/View/Progress/SprintSheetView.swift
  SoccerBeat/SoccerBeat Watch App/View/Progress/SprintView.swift
  SoccerBeat/SoccerBeat Watch App/View/StartPauseControl/PrecountView.swift
  SoccerBeat/SoccerBeat Watch App/View/StartPauseControl/SessionPagingView.swift
  SoccerBeat/SoccerBeat Watch App/View/StartPauseControl/SplitControlsView.swift
  SoccerBeat/SoccerBeat Watch App/View/StartPauseControl/StartView.swift
  SoccerBeat/SoccerBeat Watch App/View/Summary/SummaryView.swift
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/MatricsIndicator.swift
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/WatchWorkoutManager.swift
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/WorkoutManager+extensions.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/Interactors/HealthInteractor.swift
  SoccerBeat/SoccerBeat/Resources/WorkoutData.swift
Labels: refactor

#272 fix: [#268] stub 데이터를 각각의 타입에 추가해서 에러 없앰
  SoccerBeat/Share/Utiles/Dictionary+extension.swift
  SoccerBeat/Share/Utiles/Text+extension.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/Interactors/HealthInteractor.swift
  SoccerBeat/SoccerBeat/Resources/WorkoutData.swift
  SoccerBeat/SoccerBeat/UI/Screens/ContentView.swift
  SoccerBeat/SoccerBeat/UI/Screens/EmptyDataView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MainView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchDetailView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchRecapView.swift
Labels: bug

#277 refactor:[#268] 레이더 차트, WorkoutAverageData를 사용하는 뷰 재구성
  SoccerBeat/SoccerBeat Watch App/WorkoutManager/MatricsIndicator.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/Interactors/HealthInteractor.swift
  SoccerBeat/SoccerBeat/Photos/Profile.swift
  SoccerBeat/SoccerBeat/Photos/ProfileImage.swift
  SoccerBeat/SoccerBeat/Photos/ProfileModel.swift
  SoccerBeat/SoccerBeat/Resources/DataConverter.swift
  SoccerBeat/SoccerBeat/Resources/WorkoutData.swift
  SoccerBeat/SoccerBeat/SoccerBeatApp.swift
  SoccerBeat/SoccerBeat/UI/Analytics/AnalyticsComponent.swift
  SoccerBeat/SoccerBeat/UI/Charts/BPMChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/BPMChartOverview.swift
  SoccerBeat/SoccerBeat/UI/Charts/DistanceChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/DistanceChartOverview.swift
  SoccerBeat/SoccerBeat/UI/Charts/SpeedChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/SpeedChartOverview.swift
  SoccerBeat/SoccerBeat/UI/Charts/SprintChart.swift
  SoccerBeat/SoccerBeat/UI/Charts/SprintChartOverview.swift
  SoccerBeat/SoccerBeat/UI/Screens/ContentView.swift
  SoccerBeat/SoccerBeat/UI/Screens/EmptyDataView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MainView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchDetailView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchRecapView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MyCardView.swift
  SoccerBeat/SoccerBeat/UI/Screens/ProfileView.swift
  SoccerBeat/SoccerBeat/UI/Screens/RadarChartView.swift
  SoccerBeat/SoccerBeat/UI/Screens/ShareView.swift
  SoccerBeat/SoccerBeat/UI/Trophy/TrophyCollectionView.swift
Labels: enhancement

#279 fix: [#276] Radar Chart의 위치가 이상하게 잡히는 버그 수정
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/UI/Screens/MainView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchDetailView.swift
  SoccerBeat/SoccerBeat/UI/Screens/MatchRecapView.swift
  SoccerBeat/SoccerBeat/UI/Screens/ProfileView.swift
  SoccerBeat/SoccerBeat/UI/Screens/RadarChartView.swift
Labels: bug
