Repository DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo, pull requests merged in 2024-07, with the labels that each got.

#343 feat: [#341] EmptyView MainView 통합
  SoccerBeat/SoccerBeat/Sources/Features/HomeView/ContentView.swift
  SoccerBeat/SoccerBeat/Sources/Features/HomeView/MainView.swift
Labels: enhancement

#345 [Fix/gucci/339] 건강과 위치 권한 없이 워치에서 시작 버튼을 못누르게 막음
  SoccerBeat/Common/Data/HealthInteractor.swift
  SoccerBeat/SoccerBeat Watch App/SoccerBeatApp.swift
  SoccerBeat/SoccerBeat Watch App/Sources/Features/StartPauseControl/StartView.swift
  SoccerBeat/SoccerBeat Watch App/Sources/WorkoutManager/MatricsIndicator.swift
  SoccerBeat/SoccerBeat Watch App/Sources/WorkoutManager/WatchWorkoutManager.swift
  SoccerBeat/SoccerBeat Watch App/Sources/WorkoutManager/WorkoutManager+extensions.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SoccerBeat/SoccerBeat/SoccerBeatApp.swift
  SoccerBeat/SoccerBeat/en.lproj/Localizable.strings
  SoccerBeat/SoccerBeat/ko.lproj/Localizable.strings
  SoccerBeat/SoccerBeat/zh-Hans.lproj/Localizable.strings
Labels: bug

#350 fix: 데이터 저장 안되는 버그 수정
  SoccerBeat/SoccerBeat Watch App/Sources/WorkoutManager/WatchWorkoutManager.swift
Labels: bug

#355 feat: [#354] 데이터가 없을 때 OnboardingView가 나오도록 구현
  SoccerBeat/Common/Data/WorkoutData.swift
  SoccerBeat/Common/Utiles/Font+extension.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/SoccerBeatApp.swift
  SoccerBeat/SoccerBeat/Sources/Features/HomeView/ContentView.swift
  SoccerBeat/SoccerBeat/Sources/Features/HomeView/MainView.swift
  SoccerBeat/SoccerBeat/Sources/Features/HomeView/Subviews/OnboardingView.swift
  SoccerBeat/SoccerBeat/Sources/Features/MatchRecords/MatchDetailView.swift
  SoccerBeat/SoccerBeat/Sources/Features/MatchRecords/MatchRecapView.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/AnalyticsView.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/AnalyticsComponent.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/BPMChart.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/DistanceChart.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/SpeedChart.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/SprintChart.swift
Labels: enhancement

#359 [feat/gucci/358, 351] check healthkit config + 경기 종료 후 바로 명언뷰로 이동
  SoccerBeat/SoccerBeat Watch App/SoccerBeatApp.swift
  SoccerBeat/SoccerBeat Watch App/Sources/Features/EndRecording/SummaryView.swift
  SoccerBeat/SoccerBeat Watch App/Sources/Features/StartPauseControl/SplitControlsView.swift
  SoccerBeat/SoccerBeat Watch App/Sources/Features/StartPauseControl/StartView.swift
  SoccerBeat/SoccerBeat Watch App/Sources/WorkoutManager/WatchWorkoutManager.swift
  SoccerBeat/SoccerBeat Watch App/Sources/WorkoutManager/WorkoutManager+extensions.swift
Labels: enhancement

#362 fix: 명언뷰흔들리는 버그와 완료 버튼 유아이 작업
  SoccerBeat/Common/Utiles/Font+extension.swift
  SoccerBeat/SoccerBeat Watch App/Sources/Features/EndRecording/PhraseView.swift
  SoccerBeat/SoccerBeat Watch App/Sources/Features/EndRecording/SummaryView.swift
Labels: bug, enhancement

#365 feat: [#364] EmptyData Alert Localization Added
  SoccerBeat/SoccerBeat.xcodeproj/project.pbxproj
  SoccerBeat/SoccerBeat/Sources/Features/HomeView/Subviews/EmptyDataView.swift
  SoccerBeat/SoccerBeat/Sources/Features/MatchRecords/MatchRecapView.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/BPMChart.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/DistanceChart.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/SpeedChart.swift
  SoccerBeat/SoccerBeat/Sources/Features/TrendCharts/Subviews/SprintChart.swift
  SoccerBeat/SoccerBeat/en.lproj/Localizable.strings
  SoccerBeat/SoccerBeat/ko.lproj/Localizable.strings
  SoccerBeat/SoccerBeat/zh-Hans.lproj/Localizable.strings
Labels: enhancement

#368 feat: [#366] Badge 기준 정상화
  SoccerBeat/Common/Data/WorkoutData.swift
  SoccerBeat/SoccerBeat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement
